### PR TITLE
Fixed and optimized

### PR DESCRIPTION
**Pull request by hippi777**
hi there! :)

ive made a fix and some minor changes to make it more optimal, see the "fix and optimize" commit for more info

btw i tested it out, it works just fine :)

i hope u will like it, all the bests to u! :)

### CODE REVIEW

**Comment by nboughton** [comment]
Thanks, I've credited you in the submission notes on addons.mozilla.org

**Comment by hippi777** [comment]
thx as well! :) can i see that anywhere, or only ff devs/staff can see it?

(btw this is the 1st addon that ive ever played with, it was cheap fun while ive learned some new stuff :D )

**Comment by nboughton** [comment]
https://addons.mozilla.org/en-US/firefox/addon/nofbclid/

It's at the bottom left under release notes.

**Comment by hippi777** [comment]
thx :D bests! :)

**Pull request merged**
